/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : qlfile

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2016-05-22 11:07:31
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for message_lang
-- ----------------------------
DROP TABLE IF EXISTS `message_lang`;
CREATE TABLE `message_lang` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `msg_no` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `des_vn` varchar(200) CHARACTER SET utf8 DEFAULT NULL,
  `screen` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `des_en` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  `add_user_id` int(11) DEFAULT NULL,
  `add_datetime` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=470 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of message_lang
-- ----------------------------
INSERT INTO `message_lang` VALUES ('1', 'MENU001', 'KIểm tra yêu cầu XD', 'MENU', 'Inspection Required', null, null);
INSERT INTO `message_lang` VALUES ('2', 'MENU002', 'Lập yêu cầu XD', 'MENU', 'Establish Require', null, null);
INSERT INTO `message_lang` VALUES ('3', 'MENU003', 'Lịch sử yêu cầu XD', 'MENU', 'Required History', null, null);
INSERT INTO `message_lang` VALUES ('4', 'MENU004', 'Mượn bản vẽ', 'MENU', 'Borrow Drawings', null, null);
INSERT INTO `message_lang` VALUES ('5', 'MENU005', 'Phân bổ file', 'MENU', 'Allocate file', null, null);
INSERT INTO `message_lang` VALUES ('6', 'MENU006', 'In File', 'MENU', 'Print file', null, null);
INSERT INTO `message_lang` VALUES ('7', 'MENU007', 'Cấp phát file', 'MENU', 'Furnish file', null, null);
INSERT INTO `message_lang` VALUES ('8', 'MENU008', 'Admin', 'MENU', 'Admin', '1', '2016-05-21');
INSERT INTO `message_lang` VALUES ('9', 'MENU009', 'Lịch sử mượn trả file', 'MENU', 'Borrow file history', null, null);
INSERT INTO `message_lang` VALUES ('10', 'MENU010', 'Lịch sử file cũ', 'MENU', 'Old file history', null, null);
INSERT INTO `message_lang` VALUES ('11', 'MENU011', 'Convert lại pdf', 'MENU', 'Convert pdf', null, null);
INSERT INTO `message_lang` VALUES ('12', 'MENU012', 'Lịch sử phân bổ', 'MENU', 'Allocated history', null, null);
INSERT INTO `message_lang` VALUES ('13', 'MENU013', 'Danh mục bản vẽ', 'MENU', 'Drawing category', null, null);
INSERT INTO `message_lang` VALUES ('14', 'MENU014', 'Danh sách máy', 'MENU', 'Engine category', null, null);
INSERT INTO `message_lang` VALUES ('15', 'MENU015', 'Đưa bản vẽ vào máy', 'MENU', 'Engine drawing', null, null);
INSERT INTO `message_lang` VALUES ('16', 'MENU016', 'Lịch sử in file', 'MENU', 'Print history', null, null);
INSERT INTO `message_lang` VALUES ('17', 'MENU017', 'Lịch sử cấp phát file', 'MENU', 'Furnish file history', null, null);
INSERT INTO `message_lang` VALUES ('18', 'MENU018', 'Đơn vị', 'MENU', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('19', 'MENU019', 'Phòng ban', 'MENU', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('20', 'MENU020', 'Tổ nhóm', 'MENU', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('21', 'MENU021', 'User', 'MENU', 'User', null, null);
INSERT INTO `message_lang` VALUES ('22', 'MENU022', 'Thư mục', 'MENU', 'Folder', null, null);
INSERT INTO `message_lang` VALUES ('23', 'MENU023', 'Phân quyền', 'MENU', 'Grant privileges', null, null);
INSERT INTO `message_lang` VALUES ('24', 'MENU024', 'Lịch sử download', 'MENU', 'Download history', null, null);
INSERT INTO `message_lang` VALUES ('25', 'MENU025', 'Xóa đơn', 'MENU', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('26', 'MENU026', 'Xin Chào', 'MENU', 'Wellcome', null, null);
INSERT INTO `message_lang` VALUES ('28', 'MENU027', 'Thoát', 'MENU', 'Logout', null, null);
INSERT INTO `message_lang` VALUES ('30', 'MENU028', 'English', 'MENU', 'Việt Nam', null, null);
INSERT INTO `message_lang` VALUES ('32', 'MENU030', 'HỆ THỐNG XÉT DUYỆT BẢN VẼ', 'MENU', 'DRAWING APPROVAL SYSTEM', null, null);
INSERT INTO `message_lang` VALUES ('33', 'BVE001', 'Điều kiện tìm', 'BANVE', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('34', 'BVE002', 'Danh mục bản vẽ', 'BANVE', 'Drawing category', null, null);
INSERT INTO `message_lang` VALUES ('35', 'BVE003', 'Mã bản vẽ', 'BANVE', 'Drawing no', null, null);
INSERT INTO `message_lang` VALUES ('36', 'BVE004', 'Tên bản vẽ', 'BANVE', 'Drawing name', null, null);
INSERT INTO `message_lang` VALUES ('37', 'BVE005', 'Tìm', 'BANVE', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('38', 'BVE006', 'Thêm mới', 'BANVE', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('39', 'BVE007', 'Xuất excel', 'BANVE', 'Export excel', null, null);
INSERT INTO `message_lang` VALUES ('40', 'BVE008', 'Không có dữ liệu', 'BANVE', 'Not found data', null, null);
INSERT INTO `message_lang` VALUES ('41', 'BVE009', 'Cập nhật thành công !', 'BANVE', 'Save successful', null, null);
INSERT INTO `message_lang` VALUES ('42', 'BVE020', 'Bạn chưa nhập khổ giấy !', 'BANVE', 'You did not enter page size', null, null);
INSERT INTO `message_lang` VALUES ('43', 'BVE019', 'Bạn có chắc chắn muốn thoát？', 'BANVE', 'Are you sure exit  ?', null, null);
INSERT INTO `message_lang` VALUES ('44', 'BVE018', 'Bạn chắc chắn muốn xóa bản vẽ mục này？', 'BANVE', 'Are you sure delete this drawing ?', null, null);
INSERT INTO `message_lang` VALUES ('45', 'BVE017', 'Bạn chưa chọn mã bản vẽ  cấp cha !', 'BANVE', 'You did not choose parent level drawing', null, null);
INSERT INTO `message_lang` VALUES ('46', 'BVE016', 'Chọn bản vẽ cấp cha', 'BANVE', 'Select parent level drawing', null, null);
INSERT INTO `message_lang` VALUES ('47', 'BVE015', 'Bản vẽ phôi', 'BANVE', 'Embryo drawing', null, null);
INSERT INTO `message_lang` VALUES ('48', 'BVE014', 'Bản vẽ chi tiết', 'BANVE', 'Detailed drawings', null, null);
INSERT INTO `message_lang` VALUES ('49', 'BVE013', 'Bản vẽ cụm nhỏ', 'BANVE', 'Drawing small clusters', null, null);
INSERT INTO `message_lang` VALUES ('50', 'BVE012', 'Bản vẽ cụm lớn', 'BANVE', 'Drawing large clusters', null, null);
INSERT INTO `message_lang` VALUES ('51', 'BVE011', 'Bản vẽ tổng thể', 'BANVE', 'Overall drawing', null, null);
INSERT INTO `message_lang` VALUES ('52', 'BVE010', 'Cấp \"Bản vẽ phôi\" không thể tạo cấp con !', 'BANVE', 'Embryo drawing can not create child level !', null, null);
INSERT INTO `message_lang` VALUES ('53', 'BVE037', 'Tồn tại bản vẻ con, không thể xóa !', 'BANVE', 'Exists child drawing, can not delete !', null, null);
INSERT INTO `message_lang` VALUES ('54', 'BVE029', 'Mã bản vẽ \"%s\" đã có, vui lòng nhập tên khác !', 'BANVE', 'Drawing no \"%s\" is exists , please enter other name !', null, null);
INSERT INTO `message_lang` VALUES ('55', 'BVE028', 'Tên bản vẽ \"%s\" đã có, vui lòng nhập tên khác !', 'BANVE', 'Drawing name \"%s\" is exists , please enter other name !', null, null);
INSERT INTO `message_lang` VALUES ('56', 'BVE027', 'Mã bản vẽ \"%s\" chưa có, không thể tạo dùng chung, vui lòng tạo mới !', 'BANVE', 'Drawing no \"%s\" is not exists , can not create share, please add new !', null, null);
INSERT INTO `message_lang` VALUES ('57', 'BVE025', 'Copy', 'BANVE', 'Copy', null, null);
INSERT INTO `message_lang` VALUES ('58', 'BVE026', 'Tham số không hợp lệ', 'BANVE', 'Parameter invalid', null, null);
INSERT INTO `message_lang` VALUES ('59', 'BVE024', 'Bạn phải nhập khổ giấy cho bản vẽ con !', 'BANVE', 'You muslt enter page size for child drawing !', null, null);
INSERT INTO `message_lang` VALUES ('60', 'BVE023', 'Bạn phải nhập mã cho bản vẽ dùng chung !', 'BANVE', 'You must enter Shared drawing no  !', null, null);
INSERT INTO `message_lang` VALUES ('61', 'BVE022', 'Bạn chưa nhập đủ 7 ký tự cho Mã bản vẽ !', 'BANVE', 'You did not enter enought 7 character for drawing no !', null, null);
INSERT INTO `message_lang` VALUES ('62', 'BVE021', 'Bạn chưa nhập Tên bản vẽ !', 'BANVE', 'You did not enter Drawing no !', null, null);
INSERT INTO `message_lang` VALUES ('63', 'BVE036', 'Ngày tạo', 'BANVE', 'Add date', null, null);
INSERT INTO `message_lang` VALUES ('64', 'BVE035', 'Người tạo', 'BANVE', 'Add user', null, null);
INSERT INTO `message_lang` VALUES ('65', 'BVE034', 'Tên bản vẽ', 'BANVE', 'Drawing name', null, null);
INSERT INTO `message_lang` VALUES ('66', 'BVE033', 'Loại bản vẽ', 'BANVE', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('67', 'BVE032', 'Mã bản vẽ', 'BANVE', 'Drawing no', null, null);
INSERT INTO `message_lang` VALUES ('68', 'BVE031', 'Khổ giấy', 'BANVE', 'Page size', null, null);
INSERT INTO `message_lang` VALUES ('69', 'BVE030', 'Dùng chung', 'BANVE', 'Shared', null, null);
INSERT INTO `message_lang` VALUES ('70', 'BVE038', 'Có', 'BANVE', 'Yes', null, null);
INSERT INTO `message_lang` VALUES ('71', 'BVE039', 'Không', 'BANVE', 'No', null, null);
INSERT INTO `message_lang` VALUES ('72', 'BVE040', 'Xóa', 'BANVE', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('73', 'TREE001', 'Mở rộng', 'TREE', 'Unfold', null, null);
INSERT INTO `message_lang` VALUES ('74', 'TREE002', 'Thu nhỏ', 'TREE', 'Fold', null, null);
INSERT INTO `message_lang` VALUES ('75', 'BVE041', 'Mở rộng', 'BANVE', 'Unfold', null, null);
INSERT INTO `message_lang` VALUES ('76', 'BVE042', 'Thông tin bản vẽ', 'BANVE', 'Drawing Infomation', null, null);
INSERT INTO `message_lang` VALUES ('77', 'BVE043', 'Cập nhật', 'BANVE', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('78', 'BVE044', 'Đóng', 'BANVE', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('79', 'BVE045', 'Thông tin cơ bản', 'BANVE', 'Basic Infomation', null, null);
INSERT INTO `message_lang` VALUES ('80', 'BVE046', 'Danh sách bản vẽ cấp con', 'BANVE', 'Child drawing  category', null, null);
INSERT INTO `message_lang` VALUES ('81', 'BVE047', 'Thêm bản vẽ con', 'BANVE', 'Add child', null, null);
INSERT INTO `message_lang` VALUES ('82', 'LOG001', 'HỆ THỐNG XÉT DUYỆT BẢN VẼ', 'LOGIN', 'DRAWING APPROVAL SYSTEM', null, null);
INSERT INTO `message_lang` VALUES ('83', 'MENU029', 'Cài đặt', 'MENU', 'Setting', null, null);
INSERT INTO `message_lang` VALUES ('84', 'LOG002', 'Tên đăng nhập', 'LOGIN', 'User name', '1', '2016-05-22');
INSERT INTO `message_lang` VALUES ('85', 'LOG003', 'Mật khẩu', 'LOGIN', 'Password', null, null);
INSERT INTO `message_lang` VALUES ('86', 'LOG004', 'Ngôn ngữ', 'LOGIN', 'Language', null, null);
INSERT INTO `message_lang` VALUES ('87', 'LOG005', 'Xóa', 'LOGIN', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('88', 'LOG006', 'Đăng nhập', 'LOGIN', 'Login', null, null);
INSERT INTO `message_lang` VALUES ('89', 'DON001', 'No.', 'DON', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('90', 'DON002', 'Mã bản vẽ', 'DON', 'Drawing no', null, null);
INSERT INTO `message_lang` VALUES ('91', 'DON003', 'Tiêu đề', 'DON', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('92', 'DON004', 'Ngày lập', 'DON', 'Add date', null, null);
INSERT INTO `message_lang` VALUES ('93', 'DON005', 'Người tạo', 'DON', 'Add user', null, null);
INSERT INTO `message_lang` VALUES ('94', 'DON006', 'Người duyệt cuối', 'DON', 'Last approver', null, null);
INSERT INTO `message_lang` VALUES ('95', 'DON007', 'Tình trạng', 'DON', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('96', 'DON008', 'Nội dung', 'DON', 'Content', null, null);
INSERT INTO `message_lang` VALUES ('97', 'DON009', 'Loại bản vẽ', 'DON', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('98', 'DON010', 'Mã bản vẽ tổng', 'DON', 'General drawing code', null, null);
INSERT INTO `message_lang` VALUES ('99', 'DON011', 'Từ thời điểm', 'DON', 'From', null, null);
INSERT INTO `message_lang` VALUES ('100', 'DON012', 'Đến', 'DON', 'To', null, null);
INSERT INTO `message_lang` VALUES ('101', 'DON013', 'Mã số duyệt', 'DON', 'Approval code', null, null);
INSERT INTO `message_lang` VALUES ('102', 'DON014', 'Tên file', 'DON', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('103', 'DON015', 'Điều kiện', 'DON', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('104', 'DON016', 'Tìm', 'DON', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('105', 'DON017', 'Xóa', 'DON', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('106', 'DON018', 'Lịch sử xét duyệt', 'DON', 'Approval history', null, null);
INSERT INTO `message_lang` VALUES ('107', 'DON019', 'Tạo mới', 'DON', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('108', 'DON020', 'Cập nhật', 'DON', 'Update', null, null);
INSERT INTO `message_lang` VALUES ('109', 'DON021', 'Đang Chờ', 'DON', 'Wating', null, null);
INSERT INTO `message_lang` VALUES ('110', 'DON022', 'Đã duyệt', 'DON', 'Approved', null, null);
INSERT INTO `message_lang` VALUES ('111', 'DON023', 'Không duyệt', 'DON', 'Not Approved', null, null);
INSERT INTO `message_lang` VALUES ('112', 'DON024', 'Xin mượn bản vẽ', 'DON', '\r\nPlease borrow drawings', null, null);
INSERT INTO `message_lang` VALUES ('113', 'DON025', 'Trả yêu cầu xin mượn bản vẽ', 'DON', 'Return require borrow drawings', null, null);
INSERT INTO `message_lang` VALUES ('114', 'DON026', 'Đã duyệt xin mượn bản vẽ', 'DON', 'Approved borow drawings', null, null);
INSERT INTO `message_lang` VALUES ('115', 'SYS001', 'Cập nhật thành công !', 'SYS', 'Save successful !', null, null);
INSERT INTO `message_lang` VALUES ('116', 'SYS002', 'Xóa đơn thành công !', 'SYS', 'Delete successful !', null, null);
INSERT INTO `message_lang` VALUES ('117', 'SYS003', 'Đơn này đã gửi duyệt không thể xóa', 'SYS', 'This requirement was submitted for approval, can not delete !', null, null);
INSERT INTO `message_lang` VALUES ('118', 'SYS004', 'Bạn không có quyền xóa đơn này,vì bạn không phải là người tạo !', 'SYS', 'You can not delete this requirement, because you are not create it !', null, null);
INSERT INTO `message_lang` VALUES ('119', 'YEU001', 'Người lập', 'YEUCAU', 'Add user', null, null);
INSERT INTO `message_lang` VALUES ('120', 'YEU002', 'Bộ phận', 'YEUCAU', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('121', 'YEU003', 'Loại bản vẽ', 'YEUCAU', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('122', 'YEU004', 'Ngày lập', 'YEUCAU', 'Add date', null, null);
INSERT INTO `message_lang` VALUES ('123', 'YEU005', 'Mã số xét duyệt', 'YEUCAU', 'Approved code', null, null);
INSERT INTO `message_lang` VALUES ('124', 'YEU006', 'Tiêu đề', 'YEUCAU', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('125', 'YEU007', 'Mã bản vẽ tổng', 'YEUCAU', 'General drawing code', null, null);
INSERT INTO `message_lang` VALUES ('126', 'YEU008', 'Nội dung(lập mới - chỉnh sửa bản vẽ)', 'YEUCAU', 'Content(new - upadate)', null, null);
INSERT INTO `message_lang` VALUES ('127', 'YEU009', 'Đính kèm bản vẽ', 'YEUCAU', 'Attach file', null, null);
INSERT INTO `message_lang` VALUES ('128', 'YEU010', 'Chọn file', 'YEUCAU', 'Choose file', null, null);
INSERT INTO `message_lang` VALUES ('129', 'YEU011', 'Save', 'YEUCAU', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('130', 'YEU012', 'Gửi mail yêu cầu kiểm tra', 'YEUCAU', 'Send mail require check', null, null);
INSERT INTO `message_lang` VALUES ('131', 'YEU013', 'Gửi mail mượn bản vẽ', 'YEUCAU', 'Send mail borrow drawings', null, null);
INSERT INTO `message_lang` VALUES ('132', 'YEU014', 'Xóa đơn', 'YEUCAU', 'Delete requirement', null, null);
INSERT INTO `message_lang` VALUES ('133', 'YEU015', '\r\nNgười kiểm tra', 'YEUCAU', 'Checker', null, null);
INSERT INTO `message_lang` VALUES ('134', 'YEU016', 'Ngày tháng', 'YEUCAU', 'Date', null, null);
INSERT INTO `message_lang` VALUES ('135', 'YEU017', 'Người Duyệt', 'YEUCAU', 'Approver', null, null);
INSERT INTO `message_lang` VALUES ('136', 'YEU018', 'TTQL bản vẽ xét duyệt', 'YEUCAU', 'Center drawing approval', null, null);
INSERT INTO `message_lang` VALUES ('137', 'YEU019', 'Kiểm tra', 'YEUCAU', 'Check', null, null);
INSERT INTO `message_lang` VALUES ('138', 'YEU020', 'Duyệt', 'YEUCAU', 'Approval', null, null);
INSERT INTO `message_lang` VALUES ('139', 'YEU021', 'Duyệt mượn', 'YEUCAU', 'Approval borrow', null, null);
INSERT INTO `message_lang` VALUES ('140', 'YEU022', 'Trả yêu cầu chỉnh sửa', 'YEUCAU', 'Return requirement edit', null, null);
INSERT INTO `message_lang` VALUES ('141', 'YEU023', 'Lập yêu cầu xét duyệt', 'YEUCAU', 'Establish Require', null, null);
INSERT INTO `message_lang` VALUES ('142', 'YEU024', 'Tạo mới', 'YEUCAU', 'New', null, null);
INSERT INTO `message_lang` VALUES ('143', 'YEU025', 'Cập nhật', 'YEUCAU', 'Update', null, null);
INSERT INTO `message_lang` VALUES ('144', 'YEU026', 'Ngày hẹn trả', 'YEUCAU', 'Return date', '1', '2016-05-22');
INSERT INTO `message_lang` VALUES ('145', 'YEU027', 'Mượn bản vẽ', 'YEUCAU', 'Borrow drawings', null, null);
INSERT INTO `message_lang` VALUES ('146', 'YEU028', 'Lý do mượn', 'YEUCAU', 'Reason borrow', null, null);
INSERT INTO `message_lang` VALUES ('147', 'YEU029', 'Tên file', 'YEUCAU', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('148', 'YEU030', 'Lý do trả yêu cầu', 'YEUCAU', 'Reason return requirement', null, null);
INSERT INTO `message_lang` VALUES ('149', 'YEU031', 'Bạn không có quyền tạo yêu cầu mới !', 'YEUCAU', 'You can not create new requirement !', null, null);
INSERT INTO `message_lang` VALUES ('150', 'YEU032', 'Bạn chưa upload đủ file trả !', 'YEUCAU', 'You did not upload  file  enough !', null, null);
INSERT INTO `message_lang` VALUES ('151', 'YEU033', 'Bạn chưa nhập tiêu đề !', 'YEUCAU', 'You did not enter title !', null, null);
INSERT INTO `message_lang` VALUES ('152', 'YEU034', 'Bạn chưa nhập mã bản vẽ tổng !', 'YEUCAU', 'You did not enter general drawing code !', null, null);
INSERT INTO `message_lang` VALUES ('153', 'YEU035', 'Bạn chưa chọn loại bản vẽ !', 'YEUCAU', 'You did not choose drawing type !', null, null);
INSERT INTO `message_lang` VALUES ('154', 'YEU036', 'Bạn chưa nhập nội dung !', 'YEUCAU', 'You did not enter content !', null, null);
INSERT INTO `message_lang` VALUES ('155', 'YEU037', 'Bạn chưa chọn người kiểm tra !', 'YEUCAU', 'You did not choose checker !', null, null);
INSERT INTO `message_lang` VALUES ('156', 'YEU038', 'Bạn chưa chọn người duyệt !', 'YEUCAU', 'You did not choose approver !', null, null);
INSERT INTO `message_lang` VALUES ('157', 'YEU039', 'Bạn chưa chọn trung tâm quản lý đuyệt !', 'YEUCAU', 'You did not choose center drawing approval !', null, null);
INSERT INTO `message_lang` VALUES ('158', 'YEU040', 'Trả yêu cầu mượn', 'YEUCAU', 'Return requirement borrow', null, null);
INSERT INTO `message_lang` VALUES ('159', 'LSMT001', 'Điều kiện tìm', 'LSMTRA', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('160', 'LSMT002', 'Tên file', 'LSMTRA', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('161', 'LSMT003', 'Trạng thái trả', 'LSMTRA', 'Status return', null, null);
INSERT INTO `message_lang` VALUES ('162', 'LSMT004', 'Chưa trả file mượn', 'LSMTRA', 'Did not Return file', null, null);
INSERT INTO `message_lang` VALUES ('163', 'LSMT005', 'Đã trả file mượn', 'LSMTRA', 'Returned file', null, null);
INSERT INTO `message_lang` VALUES ('164', 'LSMT006', 'Tìm', 'LSMTRA', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('165', 'LSMT007', 'Xóa', 'LSMTRA', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('166', 'LSMT008', 'Danh sách file đã duyệt', 'LSMTRA', 'Approved file category', null, null);
INSERT INTO `message_lang` VALUES ('167', 'LSMT009', 'Người tạo', 'LSMTRA', 'Add user', null, null);
INSERT INTO `message_lang` VALUES ('168', 'LSMT010', 'Ngày hẹn trả', 'LSMTRA', 'Date will return', null, null);
INSERT INTO `message_lang` VALUES ('169', 'LSMT011', 'lý do mượn', 'LSMTRA', 'Reason borrow', null, null);
INSERT INTO `message_lang` VALUES ('170', 'LSMT012', 'Tiêu đề', 'LSMTRA', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('171', 'LSMT013', 'Mã bản vẽ', 'LSMTRA', 'Drawing no', null, null);
INSERT INTO `message_lang` VALUES ('172', 'LSMT014', 'Trạng thái', 'LSMTRA', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('173', 'LSMT015', 'Lịch sử mượn trả file', 'LSMTRA', 'Borrow return file history', null, null);
INSERT INTO `message_lang` VALUES ('174', 'LSMT016', 'File này đang cập nhật !', 'LSMTRA', 'This file is updating !', null, null);
INSERT INTO `message_lang` VALUES ('175', 'OLDF001', 'Điều kiện tìm', 'OLDFILE', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('176', 'OLDF002', 'Tên file', 'OLDFILE', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('177', 'OLDF003', 'Tìm', 'OLDFILE', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('178', 'OLDF004', 'Xóa', 'OLDFILE', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('179', 'OLDF005', 'Ngày cập nhật', 'OLDFILE', 'Update date', null, null);
INSERT INTO `message_lang` VALUES ('180', 'OLDF006', 'Tiêu đề', 'OLDFILE', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('181', 'OLDF007', 'Loại bản vẽ', 'OLDFILE', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('182', 'OLDF008', 'Lịch sử file cũ', 'OLDFILE', 'Old file history', null, null);
INSERT INTO `message_lang` VALUES ('183', 'OLDF009', 'Danh sách file đã duyệt', 'OLDFILE', 'Approved file category', null, null);
INSERT INTO `message_lang` VALUES ('184', 'CPDF001', 'Convert pdf', 'CVRPDF', 'Convert pdf', null, null);
INSERT INTO `message_lang` VALUES ('185', 'CPDF002', 'Điều kiện tìm', 'CVRPDF', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('186', 'CPDF003', 'Tên file', 'CVRPDF', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('187', 'CPDF004', 'Tìm', 'CVRPDF', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('188', 'CPDF005', 'Xóa', 'CVRPDF', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('189', 'CPDF006', 'Danh sách file đã duyệt', 'CVRPDF', 'Approved file category', null, null);
INSERT INTO `message_lang` VALUES ('190', 'CPDF007', 'Ngày cập nhật', 'CVRPDF', 'Update date', null, null);
INSERT INTO `message_lang` VALUES ('191', 'CPDF008', 'Tiêu đề', 'CVRPDF', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('192', 'CPDF009', 'Loại bản vẽ', 'CVRPDF', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('193', 'MUON001', 'Mượn bản vẽ', 'MUON', 'Borrow Drawings', null, null);
INSERT INTO `message_lang` VALUES ('194', 'MUON002', 'Điều kiện', 'MUON', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('195', 'MUON003', 'Tên file', 'MUON', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('196', 'MUON004', 'Tìm', 'MUON', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('197', 'MUON005', 'Xóa', 'MUON', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('198', 'MUON006', 'No.', 'MUON', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('199', 'MUON007', 'Mã bản vẻ', 'MUON', 'Drawing no', null, null);
INSERT INTO `message_lang` VALUES ('200', 'MUON008', 'Tiêu đề', 'MUON', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('201', 'MUON009', 'Ngày lập', 'MUON', 'Add date', null, null);
INSERT INTO `message_lang` VALUES ('202', 'MUON010', 'Người duyệt', 'MUON', 'Approver', null, null);
INSERT INTO `message_lang` VALUES ('203', 'MUON011', 'Tình trạng', 'MUON', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('204', 'MUON012', 'Ghi chú', 'MUON', 'Note', null, null);
INSERT INTO `message_lang` VALUES ('205', 'PBO001', 'Phân bổ file', 'PHABO', 'Allocate file', null, null);
INSERT INTO `message_lang` VALUES ('206', 'PBO002', 'Thông tin thư mục', 'PHABO', 'Folder Infomation', null, null);
INSERT INTO `message_lang` VALUES ('207', 'PBO003', 'Yêu cầu đã duyệt', 'PHABO', 'Approved requirement', null, null);
INSERT INTO `message_lang` VALUES ('208', 'PBO004', 'Yêu cầu trong Thư mục', 'PHABO', 'Requirement in folder', null, null);
INSERT INTO `message_lang` VALUES ('209', 'PBO005', 'Cập nhật', 'PHABO', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('210', 'PBO006', 'Cập nhật thành công !', 'PHABO', 'Save successful  !', null, null);
INSERT INTO `message_lang` VALUES ('211', 'LSPB001', 'Lịch sử phân bổ', 'LSPBO', 'Allocated history', null, null);
INSERT INTO `message_lang` VALUES ('212', 'LSPB002', 'Điều kiện', 'LSPBO', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('213', 'LSPB003', 'Thư mục', 'LSPBO', 'Folder', null, null);
INSERT INTO `message_lang` VALUES ('214', 'LSPB004', 'Tiêu đề', 'LSPBO', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('215', 'LSPB005', 'Tên file', 'LSPBO', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('216', 'LSPB006', 'Từ thời điểm', 'LSPBO', 'From', null, null);
INSERT INTO `message_lang` VALUES ('217', 'LSPB007', 'Đến', 'LSPBO', 'To', null, null);
INSERT INTO `message_lang` VALUES ('218', 'LSPB008', 'Tìm', 'LSPBO', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('219', 'LSPB009', 'Xóa', 'LSPBO', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('220', 'LSPB010', 'No.', 'LSPBO', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('221', 'LSPB011', 'Ngày phân bổ', 'LSPBO', 'Allocated date', null, null);
INSERT INTO `message_lang` VALUES ('222', 'MAY001', 'Danh sách máy', 'MAY', 'Engine category', null, null);
INSERT INTO `message_lang` VALUES ('223', 'MAY002', 'Điều kiện', 'MAY', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('224', 'MAY003', 'Mã máy', 'MAY', 'Engine  no', null, null);
INSERT INTO `message_lang` VALUES ('225', 'MAY004', 'Tên máy', 'MAY', 'Engine name', null, null);
INSERT INTO `message_lang` VALUES ('226', 'MAY005', 'Tìm', 'MAY', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('227', 'MAY006', 'Xóa', 'MAY', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('228', 'MAY007', 'Ngưng sử dụng', 'MAY', 'Stop', null, null);
INSERT INTO `message_lang` VALUES ('229', 'MAY008', 'Trạng thái', 'MAY', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('230', 'MAY009', 'Thêm mới Máy', 'MAY', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('231', 'MAY010', 'Sử dụng', 'MAY', 'Use', null, null);
INSERT INTO `message_lang` VALUES ('233', 'MAY012', 'Thông tin máy', 'MAY', 'Engine Infomation', null, null);
INSERT INTO `message_lang` VALUES ('234', 'MAY013', 'Cập nhật', 'MAY', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('235', 'MAY014', 'Thoát', 'MAY', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('236', 'MAY015', 'Sửa Máy', 'MAY', 'Engine edit', null, null);
INSERT INTO `message_lang` VALUES ('237', 'MAY016', 'Thêm mới', 'MAY', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('238', 'MAFI001', 'Đưa file vào máy', 'MAYFI', 'Push file to engine', null, null);
INSERT INTO `message_lang` VALUES ('239', 'MAFI002', 'Thông tin máy', 'MAYFI', 'Engine Infomation', null, null);
INSERT INTO `message_lang` VALUES ('240', 'MAFI003', 'File đã duyệt', 'MAYFI', 'Approved file', null, null);
INSERT INTO `message_lang` VALUES ('241', 'MAFI004', 'File trong máy', 'MAYFI', 'File in engine', null, null);
INSERT INTO `message_lang` VALUES ('242', 'MAFI005', 'Cập nhật', 'MAYFI', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('243', 'MAFI006', 'Cập nhật thành công !', 'MAYFI', 'Save successful  !', null, null);
INSERT INTO `message_lang` VALUES ('244', 'PRIN001', 'In file', 'PRINT', 'Print', null, null);
INSERT INTO `message_lang` VALUES ('245', 'PRIN002', 'Điều kiện tìm', 'PRINT', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('246', 'PRIN003', 'Tên file', 'PRINT', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('247', 'PRIN004', 'Tìm', 'PRINT', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('248', 'PRIN005', 'Xóa', 'PRINT', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('249', 'PRIN006', 'Danh sách file đã duyệt', 'PRINT', 'Approved file category', null, null);
INSERT INTO `message_lang` VALUES ('251', 'PRIN007', 'Tiêu đề', 'PRINT', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('252', 'PRIN008', 'Loại bản vẽ', 'PRINT', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('253', 'PRIN009', 'Người cập nhật', 'PRINT', 'Update user', null, null);
INSERT INTO `message_lang` VALUES ('254', 'PRIN010', 'Ngày cập nhật', 'PRINT', 'Update date', null, null);
INSERT INTO `message_lang` VALUES ('255', 'PRIN011', 'Người duyệt', 'PRINT', 'Approved user', null, null);
INSERT INTO `message_lang` VALUES ('256', 'PRIN012', 'Ngày duyệt', 'PRINT', 'Approved date', null, null);
INSERT INTO `message_lang` VALUES ('257', 'PRIN013', 'File này đang cập nhật !', 'PRINT', 'This file is updating !', null, null);
INSERT INTO `message_lang` VALUES ('258', 'LSPR001', 'Lịch sử in', 'LSPRT', 'Print history', null, null);
INSERT INTO `message_lang` VALUES ('259', 'LSPR002', 'Điều kiện', 'LSPRT', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('260', 'LSPR003', 'Đơn vị', 'LSPRT', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('261', 'LSPR004', 'Phòng ban', 'LSPRT', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('262', 'LSPR005', 'Tổ (nhóm)', 'LSPRT', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('263', 'LSPR006', 'Từ thời điểm', 'LSPRT', 'From', null, null);
INSERT INTO `message_lang` VALUES ('264', 'LSPR007', 'Đến', 'LSPRT', 'To', null, null);
INSERT INTO `message_lang` VALUES ('265', 'LSPR008', 'Tìm', 'LSPRT', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('266', 'LSPR009', 'Xóa', 'LSPRT', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('267', 'LSPR010', 'Theo ngày', 'LSPRT', 'Follow date', null, null);
INSERT INTO `message_lang` VALUES ('268', 'LSPR011', 'Theo số lượng tổng', 'LSPRT', 'Follow total', null, null);
INSERT INTO `message_lang` VALUES ('269', 'LSPR012', 'Tên file', 'LSPRT', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('270', 'LSPR013', 'No.', 'LSPRT', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('271', 'LSPR014', 'Ngày giờ', 'LSPRT', 'Date', null, null);
INSERT INTO `message_lang` VALUES ('272', 'LSPR015', 'Số lượng in', 'LSPRT', 'Print total', null, null);
INSERT INTO `message_lang` VALUES ('273', 'CAPP001', 'Cấp phát file', 'CAPPT', 'Furnish file', null, null);
INSERT INTO `message_lang` VALUES ('274', 'CAPP002', 'Điều kiện tìm', 'CAPPT', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('275', 'CAPP003', 'Tiêu đề', 'CAPPT', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('276', 'CAPP004', 'Tên file', 'CAPPT', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('277', 'CAPP005', 'Tìm', 'CAPPT', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('278', 'CAPP006', 'Xóa', 'CAPPT', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('279', 'CAPP007', 'Danh sách file đã duyệt', 'CAPPT', 'Approved file category', null, null);
INSERT INTO `message_lang` VALUES ('280', 'CAPP008', 'Ngày cập nhật', 'CAPPT', 'Update date', null, null);
INSERT INTO `message_lang` VALUES ('281', 'CAPP009', 'Mã bản vẽ tổng', 'CAPPT', 'General drawing code', null, null);
INSERT INTO `message_lang` VALUES ('282', 'CAPP010', 'Loại bản vẽ', 'CAPPT', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('283', 'CAPP011', 'Cấp phát', 'CAPPT', 'Furnish', null, null);
INSERT INTO `message_lang` VALUES ('284', 'CAPP012', 'Cập nhật thành công !', 'CAPPT', 'Save successful !', null, null);
INSERT INTO `message_lang` VALUES ('285', 'CAPP013', 'Thoát', 'CAPPT', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('286', 'CAPP014', 'Cập nhật', 'CAPPT', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('287', 'CAPP015', 'Thêm', 'CAPPT', 'Add', null, null);
INSERT INTO `message_lang` VALUES ('288', 'CAPP016', 'Đơn vị', 'CAPPT', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('289', 'CAPP017', 'Phòng ban', 'CAPPT', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('290', 'CAPP018', 'Tổ nhóm', 'CAPPT', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('291', 'CAPP019', 'Số lượng', 'CAPPT', 'Quality', null, null);
INSERT INTO `message_lang` VALUES ('292', 'LSCP001', 'Lịch sử cấp phát', 'LSCAPP', 'Furnish file history', null, null);
INSERT INTO `message_lang` VALUES ('293', 'LSCP002', 'Điều kiện', 'LSCAPP', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('294', 'LSCP003', 'Đơn vị', 'LSCAPP', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('295', 'LSCP004', 'Phòng ban', 'LSCAPP', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('296', 'LSCP005', 'Tổ (nhóm)', 'LSCAPP', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('297', 'LSCP006', 'Từ thời điểm', 'LSCAPP', 'From', null, null);
INSERT INTO `message_lang` VALUES ('298', 'LSCP007', 'Đến', 'LSCAPP', 'To', null, null);
INSERT INTO `message_lang` VALUES ('299', 'LSCP008', 'Tìm', 'LSCAPP', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('300', 'LSCP009', 'Xóa', 'LSCAPP', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('301', 'LSCP010', 'Theo ngày', 'LSCAPP', 'Follow date', null, null);
INSERT INTO `message_lang` VALUES ('302', 'LSCP011', 'Theo số lượng tổng', 'LSCAPP', 'Follow total', null, null);
INSERT INTO `message_lang` VALUES ('303', 'LSCP012', 'Tên file', 'LSCAPP', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('304', 'LSCP013', 'No.', 'LSCAPP', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('305', 'LSCP014', 'Ngày giờ', 'LSCAPP', 'Date', null, null);
INSERT INTO `message_lang` VALUES ('306', 'LSCP015', 'Số lượng cấp phát', 'LSCAPP', 'Print total', null, null);
INSERT INTO `message_lang` VALUES ('307', 'DOVI001', 'Đơn vị', 'DONVI', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('308', 'DOVI002', 'Điều kiện', 'DONVI', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('309', 'DOVI003', 'Tên đơn vị', 'DONVI', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('310', 'DOVI004', 'Danh sách đơn vị', 'DONVI', 'Branch category', null, null);
INSERT INTO `message_lang` VALUES ('311', 'DOVI005', 'Ngưng sử dụng', 'DONVI', 'Stop', null, null);
INSERT INTO `message_lang` VALUES ('312', 'DOVI006', 'Thêm mới', 'DONVI', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('313', 'DOVI007', 'Trạng thái', 'DONVI', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('314', 'DOVI008', 'Thông tin đơn vị', 'DONVI', 'Branch infomation', null, null);
INSERT INTO `message_lang` VALUES ('315', 'DOVI009', 'Cập nhật', 'DONVI', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('316', 'DOVI010', 'Thoát', 'DONVI', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('317', 'DOVI011', 'Tìm ', 'DONVI', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('318', 'DOVI012', 'Xóa', 'DONVI', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('319', 'DOVI013', 'Thêm mới đơn vị', 'DONVI', 'Add new Branch', null, null);
INSERT INTO `message_lang` VALUES ('320', 'DOVI014', 'Sửa đơn vị', 'DONVI', 'Edit Branch', null, null);
INSERT INTO `message_lang` VALUES ('321', 'PBAN001', 'Phòng ban', 'PBAN', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('322', 'PBAN002', 'Điều kiện', 'PBAN', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('323', 'PBAN003', 'Tên phòng ban', 'PBAN', 'Department name', null, null);
INSERT INTO `message_lang` VALUES ('324', 'PBAN004', 'Tìm ', 'PBAN', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('325', 'PBAN005', 'Xóa', 'PBAN', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('326', 'PBAN006', 'Đơn vị', 'PBAN', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('327', 'PBAN007', 'Danh sách phòng ban', 'PBAN', 'Branch category', null, null);
INSERT INTO `message_lang` VALUES ('328', 'PBAN008', 'Ngưng sử dụng', 'PBAN', 'Stop', null, null);
INSERT INTO `message_lang` VALUES ('329', 'PBAN009', 'Thêm mới', 'PBAN', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('330', 'PBAN010', 'Trạng thái', 'PBAN', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('331', 'PBAN011', 'Thông tin phòng ban', 'PBAN', 'Department infomation', null, null);
INSERT INTO `message_lang` VALUES ('332', 'PBAN012', 'Thêm mới phòng ban', 'PBAN', 'Add new Department', null, null);
INSERT INTO `message_lang` VALUES ('333', 'PBAN013', 'Cập nhật', 'PBAN', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('334', 'PBAN014', 'Thoát', 'PBAN', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('335', 'PBAN015', 'Sửa phòng ban', 'PBAN', 'Edit Department', null, null);
INSERT INTO `message_lang` VALUES ('336', 'PBAN016', 'sử dụng', 'PBAN', 'Use', null, null);
INSERT INTO `message_lang` VALUES ('337', 'PBAN017', 'Ngưng sử dụng', 'PBAN', 'Stop', null, null);
INSERT INTO `message_lang` VALUES ('339', 'DOVI015', 'Sử dụng', 'DONVI', 'Use', null, null);
INSERT INTO `message_lang` VALUES ('340', 'GRO001', 'Tổ nhóm', 'GROUP', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('341', 'GRO002', 'Điều kiện', 'GROUP', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('342', 'GRO003', 'Tên tổ (nhóm)', 'GROUP', 'Group name', null, null);
INSERT INTO `message_lang` VALUES ('343', 'GRO004', 'Tìm ', 'GROUP', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('344', 'GRO005', 'Xóa', 'GROUP', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('345', 'GRO006', 'Phòng ban', 'GROUP', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('346', 'GRO007', 'Đơn vị', 'GROUP', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('347', 'GRO008', 'Ngưng sử dụng', 'GROUP', 'Stop', null, null);
INSERT INTO `message_lang` VALUES ('348', 'GRO009', 'sử dụng', 'GROUP', 'Use', null, null);
INSERT INTO `message_lang` VALUES ('349', 'GRO010', 'Danh sách tổ (nhóm)', 'GROUP', 'Group category', null, null);
INSERT INTO `message_lang` VALUES ('350', 'GRO011', 'Thêm mới', 'GROUP', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('351', 'GRO012', 'Trạng thái', 'GROUP', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('352', 'GRO013', 'Thông tin tổ (nhóm)', 'GROUP', 'Group infomation', null, null);
INSERT INTO `message_lang` VALUES ('353', 'GRO014', 'Thêm mới tổ (nhóm)', 'GROUP', 'Add new Group', null, null);
INSERT INTO `message_lang` VALUES ('354', 'GRO015', 'Cập nhật', 'GROUP', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('355', 'GRO016', 'Thoát', 'GROUP', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('356', 'GRO017', 'Sửa tổ (nhóm)', 'GROUP', 'Edit Group', null, null);
INSERT INTO `message_lang` VALUES ('357', 'USER001', 'User', 'USER', 'User', null, null);
INSERT INTO `message_lang` VALUES ('358', 'USER002', 'Điều kiện', 'USER', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('359', 'USER003', 'Tên đăng nhập', 'USER', 'User name', null, null);
INSERT INTO `message_lang` VALUES ('360', 'USER004', 'Tìm ', 'USER', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('361', 'USER005', 'Xóa', 'USER', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('362', 'USER006', 'Họ và tên', 'USER', 'Full name', null, null);
INSERT INTO `message_lang` VALUES ('363', 'USER007', 'Email', 'USER', 'Email', null, null);
INSERT INTO `message_lang` VALUES ('364', 'USER008', 'Phòng ban', 'USER', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('365', 'USER009', 'Đơn vị', 'USER', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('366', 'USER010', 'Tổ nhóm', 'USER', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('367', 'USER011', 'Ngưng sử dụng', 'USER', 'Stop', null, null);
INSERT INTO `message_lang` VALUES ('368', 'USER012', 'sử dụng', 'USER', 'Use', null, null);
INSERT INTO `message_lang` VALUES ('369', 'USER013', 'Danh sách user', 'USER', 'User category', null, null);
INSERT INTO `message_lang` VALUES ('370', 'USER014', 'Thêm mới', 'USER', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('371', 'USER015', 'Mật khẩu', 'USER', 'Password', null, null);
INSERT INTO `message_lang` VALUES ('372', 'USER016', 'IP máy', 'USER', 'IP', null, null);
INSERT INTO `message_lang` VALUES ('373', 'USER017', 'Quyền user', 'USER', 'Privileges', null, null);
INSERT INTO `message_lang` VALUES ('374', 'USER018', 'In', 'USER', 'Print', null, null);
INSERT INTO `message_lang` VALUES ('375', 'USER019', 'Upload', 'USER', 'Upload', null, null);
INSERT INTO `message_lang` VALUES ('376', 'USER020', 'Kiểm tra', 'USER', 'Chek', null, null);
INSERT INTO `message_lang` VALUES ('377', 'USER021', 'Duyệt', 'USER', 'Approval', null, null);
INSERT INTO `message_lang` VALUES ('378', 'USER022', 'Trung tâm quản lý', 'USER', 'Center drawing', null, null);
INSERT INTO `message_lang` VALUES ('379', 'USER023', 'Admin', 'USER', 'Admin', null, null);
INSERT INTO `message_lang` VALUES ('380', 'USER024', 'Trạng thái', 'USER', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('381', 'USER025', 'Thông tin User', 'USER', 'User infomation', null, null);
INSERT INTO `message_lang` VALUES ('382', 'USER026', 'Thêm mới User', 'USER', 'Add new User', null, null);
INSERT INTO `message_lang` VALUES ('383', 'USER027', 'Cập nhật', 'USER', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('384', 'USER028', 'Thoát', 'USER', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('385', 'USER029', 'Sửa User', 'USER', 'Edit User', null, null);
INSERT INTO `message_lang` VALUES ('387', 'USER030', 'Tên đăng nhập này đã có, vui lòng nhập tên khác', 'USER', 'This user name is exists, please enter other name !', null, null);
INSERT INTO `message_lang` VALUES ('388', 'USER031', 'Thay đổi mật khẩu', 'USER', 'Change password', null, null);
INSERT INTO `message_lang` VALUES ('389', 'FOLD001', 'Danh sách thư mục', 'FOLDER', 'Folder category', null, null);
INSERT INTO `message_lang` VALUES ('390', 'FOLD002', 'Thêm mới', 'FOLDER', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('391', 'FOLD003', 'Thông tin thư mục', 'FOLDER', 'Folder infomation', null, null);
INSERT INTO `message_lang` VALUES ('392', 'FOLD004', 'Đóng', 'FOLDER', 'Close', null, null);
INSERT INTO `message_lang` VALUES ('393', 'FOLD005', 'Xóa', 'FOLDER', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('394', 'FOLD006', 'Cập nhật', 'FOLDER', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('395', 'FOLD007', 'Thông tin cơ bản', 'FOLDER', 'Basic infomation', null, null);
INSERT INTO `message_lang` VALUES ('396', 'FOLD008', 'Tên thư mục', 'FOLDER', 'Folder name', null, null);
INSERT INTO `message_lang` VALUES ('397', 'FOLD009', 'Thêm thư mục con', 'FOLDER', 'Add sub folder', null, null);
INSERT INTO `message_lang` VALUES ('398', 'FOLD010', 'Danh sách thư mục con', 'FOLDER', 'Sub folder category', null, null);
INSERT INTO `message_lang` VALUES ('399', 'FOLD011', 'Không có dữ liệu', 'FOLDER', 'Data not found !', null, null);
INSERT INTO `message_lang` VALUES ('400', 'FOLD012', 'Cập nhật thành công !', 'FOLDER', 'Save   successful !', null, null);
INSERT INTO `message_lang` VALUES ('401', 'PHANQ001', 'Phân quyền', 'PHANQ', 'Grant privileges', null, null);
INSERT INTO `message_lang` VALUES ('402', 'PHANQ002', 'Cập nhật', 'PHANQ', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('403', 'PHANQ003', 'Phòng ban/ Tổ (nhóm)', 'PHANQ', 'Department / Group', null, null);
INSERT INTO `message_lang` VALUES ('404', 'PHANQ004', 'Phòng ban/ Tổ (nhóm) trong thư mục', 'PHANQ', 'Department / Group in folder', null, null);
INSERT INTO `message_lang` VALUES ('405', 'PHANQ005', 'Cập nhật thành công !', 'PHANQ', 'Save successful !', null, null);
INSERT INTO `message_lang` VALUES ('406', 'LSDW001', 'Lịch sử download', 'LSDWN', 'Download history', null, null);
INSERT INTO `message_lang` VALUES ('407', 'LSDW002', 'Điều kiện', 'LSDWN', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('408', 'LSDW003', 'Đơn vị', 'LSDWN', 'Branch', null, null);
INSERT INTO `message_lang` VALUES ('409', 'LSDW004', 'User', 'LSDWN', 'User', null, null);
INSERT INTO `message_lang` VALUES ('410', 'LSDW005', 'Phòng ban', 'LSDWN', 'Department', null, null);
INSERT INTO `message_lang` VALUES ('411', 'LSDW006', 'Tổ (nhóm)', 'LSDWN', 'Group', null, null);
INSERT INTO `message_lang` VALUES ('412', 'LSDW007', 'Từ thời điểm', 'LSDWN', 'From', null, null);
INSERT INTO `message_lang` VALUES ('413', 'LSDW008', 'Đến', 'LSDWN', 'To', null, null);
INSERT INTO `message_lang` VALUES ('414', 'LSDW009', 'Tìm', 'LSDWN', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('415', 'LSDW010', 'Xóa', 'LSDWN', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('416', 'LSDW011', 'Theo ngày', 'LSDWN', 'Follow date', null, null);
INSERT INTO `message_lang` VALUES ('417', 'LSDW012', 'Theo số lượng tổng', 'LSDWN', 'Follow total', null, null);
INSERT INTO `message_lang` VALUES ('418', 'LSDW013', 'Tên file', 'LSDWN', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('419', 'LSDW014', 'No.', 'LSDWN', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('422', 'LSDW015', 'Ngày giờ', 'LSDWN', 'Date', null, null);
INSERT INTO `message_lang` VALUES ('423', 'LSDW016', 'Số lần download ', 'LSDWN', 'Download total', null, null);
INSERT INTO `message_lang` VALUES ('424', 'DELD001', 'Xóa đơn', 'DELDON', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('425', 'DELD002', 'Điều kiện', 'DELDON', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('426', 'DELD003', 'Loại bản vẽ', 'DELDON', 'Drawing type', null, null);
INSERT INTO `message_lang` VALUES ('427', 'DELD004', 'Từ thời điểm', 'DELDON', 'From', null, null);
INSERT INTO `message_lang` VALUES ('428', 'DELD005', 'Đến', 'DELDON', 'To', null, null);
INSERT INTO `message_lang` VALUES ('429', 'DELD006', 'Tình trạng', 'DELDON', 'Status', null, null);
INSERT INTO `message_lang` VALUES ('430', 'DELD007', 'Đang Chờ', 'DELDON', 'Wating', null, null);
INSERT INTO `message_lang` VALUES ('431', 'DELD008', 'Đã duyệt', 'DELDON', 'Approved', null, null);
INSERT INTO `message_lang` VALUES ('432', 'DELD009', 'Không duyệt', 'DELDON', 'Not Approved', null, null);
INSERT INTO `message_lang` VALUES ('433', 'DELD010', 'Xin mượn bản vẽ', 'DELDON', 'Please borrow drawings', null, null);
INSERT INTO `message_lang` VALUES ('434', 'DELD011', 'Trả yêu cầu xin mượn bản vẽ', 'DELDON', 'Return require borrow drawings', null, null);
INSERT INTO `message_lang` VALUES ('435', 'DELD012', 'Đã duyệt xin mượn bản vẽ', 'DELDON', 'Approved borow drawings', null, null);
INSERT INTO `message_lang` VALUES ('436', 'DELD013', 'Tìm', 'DELDON', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('437', 'DELD014', 'Xóa', 'DELDON', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('438', 'DELD015', 'Mã bản vẽ tổng', 'DELDON', 'General drawing code', null, null);
INSERT INTO `message_lang` VALUES ('439', 'DELD016', 'Mã số duyệt', 'DELDON', 'Approval code', null, null);
INSERT INTO `message_lang` VALUES ('440', 'DELD017', 'Tên file', 'DELDON', 'File name', null, null);
INSERT INTO `message_lang` VALUES ('441', 'DELD018', 'No.', 'DELDON', 'No.', null, null);
INSERT INTO `message_lang` VALUES ('442', 'DELD019', 'Mã bản vẽ', 'DELDON', 'Drawing no', null, null);
INSERT INTO `message_lang` VALUES ('443', 'DELD020', 'Tiêu đề', 'DELDON', 'Title', null, null);
INSERT INTO `message_lang` VALUES ('444', 'DELD021', 'Ngày lập', 'DELDON', 'Add date', null, null);
INSERT INTO `message_lang` VALUES ('445', 'DELD022', 'Người duyệt', 'DELDON', 'Approver', null, null);
INSERT INTO `message_lang` VALUES ('446', 'DELD023', 'Nội dung', 'DELDON', 'Content', null, null);
INSERT INTO `message_lang` VALUES ('447', 'DELD024', 'Xóa đơn', 'DELDON', 'Delete requirement', null, null);
INSERT INTO `message_lang` VALUES ('448', 'DELD025', 'Tạo mới', 'DELDON', 'New', null, null);
INSERT INTO `message_lang` VALUES ('449', 'DELD026', 'Cập nhật', 'DELDON', 'Update', null, null);
INSERT INTO `message_lang` VALUES ('450', 'SET001', 'Cài đặt', 'SETTING', 'Setting', null, null);
INSERT INTO `message_lang` VALUES ('451', 'SET002', 'Điều kiện tìm', 'SETTING', 'Condition', null, null);
INSERT INTO `message_lang` VALUES ('452', 'SET003', 'Tên màn hình', 'SETTING', 'Screen name', null, null);
INSERT INTO `message_lang` VALUES ('453', 'SET004', 'Chuỗi thông báo', 'SETTING', 'Message', null, null);
INSERT INTO `message_lang` VALUES ('454', 'SET005', 'Tìm', 'SETTING', 'Find', null, null);
INSERT INTO `message_lang` VALUES ('455', 'SET006', 'Xóa', 'SETTING', 'Delete', null, null);
INSERT INTO `message_lang` VALUES ('456', 'SET007', 'Thêm mới', 'SETTING', 'Add new', null, null);
INSERT INTO `message_lang` VALUES ('457', 'SET008', 'Cập nhật', 'SETTING', 'Save', null, null);
INSERT INTO `message_lang` VALUES ('458', 'SET009', 'Sửa', 'SETTING', 'Edit', null, null);
INSERT INTO `message_lang` VALUES ('459', 'SET010', 'Mã thông báo', 'SETTING', 'Message no', null, null);
INSERT INTO `message_lang` VALUES ('460', 'SET011', 'Tiếng việt', 'SETTING', 'Vietnamese', null, null);
INSERT INTO `message_lang` VALUES ('461', 'SET012', 'Tiếng Anh', 'SETTING', 'English', null, null);
INSERT INTO `message_lang` VALUES ('462', 'SET013', 'Cập nhật thành công !', 'SETTING', 'Save successful !', null, null);
INSERT INTO `message_lang` VALUES ('463', 'SYS005', 'File: \"%s\" bị trùng, không thể upload !', 'SYS', 'File: \"%s\" is exists, can not upload !', null, null);
INSERT INTO `message_lang` VALUES ('464', 'SYS006', 'Upload thành công !', 'SYS', 'Upload successful !', null, null);
INSERT INTO `message_lang` VALUES ('465', 'SYS007', 'File: \"%s\" không dúng tên file cập nhật !', 'SYS', 'File: \"%s\" can not same updated file !', null, null);
INSERT INTO `message_lang` VALUES ('466', 'SYS008', 'Lỗi, không xóa được file !', 'SYS', 'Error , Can not deleted file !', null, null);
INSERT INTO `message_lang` VALUES ('467', 'SYS009', 'Tên đơn vị không được quá 50 ký tự', 'SYS', 'Branch can not long than 50 character !', null, null);
INSERT INTO `message_lang` VALUES ('468', 'SYS010', 'File: \"%s\" Không có trong đơn cũ, không thể cập nhật !', 'SYS', 'File: \"%s\" not exists in old requirement, can not update !', null, null);
INSERT INTO `message_lang` VALUES ('469', 'SYS011', 'File: \"$s\" bị trùng, không thể thêm mới, vui lòng chọn file khác hoặc Xin mượn bản vẽ !', 'SYS', 'File: \"$s\" is exist, can not add new, plaese choose other file or borrow drawing ! ', null, null);
-- ----------------------------
-- Table structure for screen
-- ----------------------------
DROP TABLE IF EXISTS `screen`;
CREATE TABLE `screen` (
  `screen_id` int(11) NOT NULL AUTO_INCREMENT,
  `screen_no` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `screen_name` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`screen_id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of screen
-- ----------------------------
INSERT INTO `screen` VALUES ('1', 'MENU', 'Menu');
INSERT INTO `screen` VALUES ('2', 'BANVE', 'Danh mục bản vẽ');
INSERT INTO `screen` VALUES ('3', 'TREE', 'Cây thư mục');
INSERT INTO `screen` VALUES ('4', 'LOGIN', 'Đăng nhập');
INSERT INTO `screen` VALUES ('5', 'DON', 'Lịch sử yêu cầu XD');
INSERT INTO `screen` VALUES ('6', 'MAYFI', 'Đua file vào máy');
INSERT INTO `screen` VALUES ('7', 'YEUCAU', 'Lập yêu cầu XD');
INSERT INTO `screen` VALUES ('8', 'LSMTRA', 'Lịch sử mượn trả file');
INSERT INTO `screen` VALUES ('9', 'OLDFILE', 'Lịch sử file cũ');
INSERT INTO `screen` VALUES ('10', 'CVRPDF', 'Convert lại pdf');
INSERT INTO `screen` VALUES ('11', 'MUON', 'Mượn bản vẽ');
INSERT INTO `screen` VALUES ('12', 'PHABO', 'Phân bổ file');
INSERT INTO `screen` VALUES ('13', 'LSPBO', 'Lịch sử phân bổ');
INSERT INTO `screen` VALUES ('14', 'MAY', 'Danh sách máy');
INSERT INTO `screen` VALUES ('15', 'PRINT', 'In file');
INSERT INTO `screen` VALUES ('16', 'LSPRT', 'Lịch sử in file');
INSERT INTO `screen` VALUES ('17', 'CAPPT', 'Cấp phát file');
INSERT INTO `screen` VALUES ('18', 'LSCAPP', 'Lịch sử cấp phát file');
INSERT INTO `screen` VALUES ('19', 'DONVI', 'Đơn vị');
INSERT INTO `screen` VALUES ('20', 'PBAN', 'Phòng ban');
INSERT INTO `screen` VALUES ('21', 'GROUP', 'Tổ nhóm');
INSERT INTO `screen` VALUES ('22', 'USER', 'User');
INSERT INTO `screen` VALUES ('23', 'FOLDER', 'Thư mục');
INSERT INTO `screen` VALUES ('24', 'PHANQ', 'Phân quyền');
INSERT INTO `screen` VALUES ('25', 'LSDWN', 'Lịch sử download');
INSERT INTO `screen` VALUES ('26', 'DELDON', 'Xóa đơn');
INSERT INTO `screen` VALUES ('27', 'SETTING', 'Cài đặt');
INSERT INTO `screen` VALUES ('28', 'SYS', 'Code trong PHP');
------------
ALTER TABLE `file`
DROP COLUMN `convert_flg`,
ADD COLUMN `convert_flg`  int(1) NULL DEFAULT 0 AFTER `file_exist`;
----
update file
set convert_flg= 1
where file_type ='pdf';
-----
update file
set convert_flg= 0
where file_type <>'pdf';